### ISSUE TITLE
NGINX version should be parameterized or use a mustache file

### ISSUE THREAD

**Issue by ashvds** [helix-collective/camus2#3]
Currently upgrading NGINX requires a code change in Camus 2.
Moving the Docker compose to use a mustache template file rather than hard coding it would make it trivial to upgrade NGINX. Alternatively, making nginx version a parameter, would allow any running version of camus2 to upgrade the nginx version used in situ

**Comment by timbod7** [comment]
Fixed with https://github.com/helix-collective/camus2/commit/a4f6c23a3a49540ad3d078c5a1ce09ac163f289b
